version: '3'

services:
  telegrabber:
    build: .
    container_name: telegrabber
    network_mode: host
    restart: always
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai